export const HomeWhyUsSlidesData = [
  {
    imgSrc: "",
    imgAlt: "",
    heading: "Lorem Ipsum 1",
    pera: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, eos? Nisi, provident repellendus quasi molestias doloribus cupiditate illo perferendis voluptates reiciendis aut sint nemo culpa, magni quibusdam, consectetur quam suscipit sapiente vel. Dicta repellendus minima doloremque facilis. Fugit, neque aliquid..",
  },
  {
    imgSrc: "",
    imgAlt: "",
    heading: "Lorem Ipsum 2",
    pera: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, eos? Nisi, provident repellendus quasi molestias doloribus cupiditate illo perferendis voluptates reiciendis aut sint nemo culpa, magni quibusdam, consectetur quam suscipit sapiente vel. Dicta repellendus minima doloremque facilis. Fugit, neque aliquid..",
  },
  {
    imgSrc: "",
    imgAlt: "",
    heading: "Lorem Ipsum 3",
    pera: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, eos? Nisi, provident repellendus quasi molestias doloribus cupiditate illo perferendis voluptates reiciendis aut sint nemo culpa, magni quibusdam, consectetur quam suscipit sapiente vel. Dicta repellendus minima doloremque facilis. Fugit, neque aliquid..",
  },
  {
    imgSrc: "",
    imgAlt: "",
    heading: "Lorem Ipsum 4",
    pera: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, eos? Nisi, provident repellendus quasi molestias doloribus cupiditate illo perferendis voluptates reiciendis aut sint nemo culpa, magni quibusdam, consectetur quam suscipit sapiente vel. Dicta repellendus minima doloremque facilis. Fugit, neque aliquid..",
  },
  {
    imgSrc: "",
    imgAlt: "",
    heading: "Lorem Ipsum 5",
    pera: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, eos? Nisi, provident repellendus quasi molestias doloribus cupiditate illo perferendis voluptates reiciendis aut sint nemo culpa, magni quibusdam, consectetur quam suscipit sapiente vel. Dicta repellendus minima doloremque facilis. Fugit, neque aliquid..",
  },
];

export const randomKeywordsObj = {
  set1: [
    "ocean",
    "🌊",
    "galaxy",
    "🚀",
    "vintage",
    "twilight",
    "breeze",
    "🌌",
    "ember",
    "🔥",
    "wander",
    "mosaic",
    "🎨",
    "aurora",
    "zenith",
    "🌟",
    "solstice",
    "cascade",
    "luminous",
    "✨",
  ],
  set2: [
    "haven",
    "🏝️",
    "odyssey",
    "🌍",
    "horizon",
    "serenity",
    "harvest",
    "🌾",
    "pioneer",
    "🧭",
    "blossom",
    "🌸",
    "meadow",
    "🌿",
    "canyon",
    "🏞️",
    "summit",
    "🏔️",
    "ripple",
    "💧",
  ],
  set3: [
    "frost",
    "❄️",
    "emberlight",
    "🔥",
    "starlit",
    "🌠",
    "sunrise",
    "🌅",
    "mist",
    "💨",
    "glimmer",
    "✨",
    "echo",
    "🔊",
    "voyage",
    "⛵",
    "whisper",
    "💬",
    "dusk",
    "🌇",
  ],
};

export const productSlidesData = [
  {
    imgSrc: "/cow-grasing-and-milking.png",
    imgAlt: "Milking Cow",
    productName: "A2 Desi Cow Milk",
    productDescription:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores provident minima quas ea architecto placeat! Soluta asperiores cumque totam nemo aliquam, veniam officia illo repellat quod. Perspiciatis ab enim incidunt architecto repellat esse, libero qui dicta in aliquid eius iure!",
    pageLink: "/product/a2-desi-cow-milk",
  },
  {
    imgSrc: "/cow-grasing-and-milking.png",
    imgAlt: "Milking Cow",
    productName: "A2 Desi Cow Milk",
    productDescription:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores provident minima quas ea architecto placeat! Soluta asperiores cumque totam nemo aliquam, veniam officia illo repellat quod. Perspiciatis ab enim incidunt architecto repellat esse, libero qui dicta in aliquid eius iure!",
    pageLink: "/product/a2-desi-cow-milk",
  },
  {
    imgSrc: "/cow-grasing-and-milking.png",
    imgAlt: "Milking Cow",
    productName: "A2 Desi Cow Milk",
    productDescription:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores provident minima quas ea architecto placeat! Soluta asperiores cumque totam nemo aliquam, veniam officia illo repellat quod. Perspiciatis ab enim incidunt architecto repellat esse, libero qui dicta in aliquid eius iure!",
    pageLink: "/product/a2-desi-cow-milk",
  },
  {
    imgSrc: "/cow-grasing-and-milking.png",
    imgAlt: "Milking Cow",
    productName: "A2 Desi Cow Milk",
    productDescription:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores provident minima quas ea architecto placeat! Soluta asperiores cumque totam nemo aliquam, veniam officia illo repellat quod. Perspiciatis ab enim incidunt architecto repellat esse, libero qui dicta in aliquid eius iure!",
    pageLink: "/product/a2-desi-cow-milk",
  },
  {
    imgSrc: "/cow-grasing-and-milking.png",
    imgAlt: "Milking Cow",
    productName: "A2 Desi Cow Milk",
    productDescription:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores provident minima quas ea architecto placeat! Soluta asperiores cumque totam nemo aliquam, veniam officia illo repellat quod. Perspiciatis ab enim incidunt architecto repellat esse, libero qui dicta in aliquid eius iure!",
    pageLink: "/product/a2-desi-cow-milk",
  },
  {
    imgSrc: "/cow-grasing-and-milking.png",
    imgAlt: "Milking Cow",
    productName: "A2 Desi Cow Milk",
    productDescription:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores provident minima quas ea architecto placeat! Soluta asperiores cumque totam nemo aliquam, veniam officia illo repellat quod. Perspiciatis ab enim incidunt architecto repellat esse, libero qui dicta in aliquid eius iure!",
    pageLink: "/product/a2-desi-cow-milk",
  },
  {
    imgSrc: "/cow-grasing-and-milking.png",
    imgAlt: "Milking Cow",
    productName: "A2 Desi Cow Milk",
    productDescription:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores provident minima quas ea architecto placeat! Soluta asperiores cumque totam nemo aliquam, veniam officia illo repellat quod. Perspiciatis ab enim incidunt architecto repellat esse, libero qui dicta in aliquid eius iure!",
    pageLink: "/product/a2-desi-cow-milk",
  },
  {
    imgSrc: "/cow-grasing-and-milking.png",
    imgAlt: "Milking Cow",
    productName: "A2 Desi Cow Milk",
    productDescription:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores provident minima quas ea architecto placeat! Soluta asperiores cumque totam nemo aliquam, veniam officia illo repellat quod. Perspiciatis ab enim incidunt architecto repellat esse, libero qui dicta in aliquid eius iure!",
    pageLink: "/product/a2-desi-cow-milk",
  },
  {
    imgSrc: "/cow-grasing-and-milking.png",
    imgAlt: "Milking Cow",
    productName: "A2 Desi Cow Milk",
    productDescription:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores provident minima quas ea architecto placeat! Soluta asperiores cumque totam nemo aliquam, veniam officia illo repellat quod. Perspiciatis ab enim incidunt architecto repellat esse, libero qui dicta in aliquid eius iure!",
    pageLink: "/product/a2-desi-cow-milk",
  },
];

export const testimonialCards = [
  {
    starcolor: "",
    description: "",
    name: "",
    designation: "",
    textcolor: "",
    bgColor: "",
  },
  {
    starcolor: "",
    description: "",
    name: "",
    designation: "",
    textcolor: "",
    bgColor: "",
  },
  {
    starcolor: "",
    description: "",
    name: "",
    designation: "",
    textcolor: "",
    bgColor: "",
  },
  {
    starcolor: "",
    description: "",
    name: "",
    designation: "",
    textcolor: "",
    bgColor: "",
  },
  {
    starcolor: "",
    description: "",
    name: "",
    designation: "",
    textcolor: "",
    bgColor: "",
  },
];
