export const productsData = [
{
  bgkeyword: "Organic",
  bgColor: "rgb(177, 153, 140)",
  name: "A2 Desi Cow Milk",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["500 ml"],
  productPageLink: "/a2-desi-cow-milk",
  imgSrc: "/",
  imgAlt: "Vardaan Farms A2 Desi Cow Milk",
  productBenefit: "Natural & Clean",
},
{
  bgkeyword: "Natural",
  bgColor: "rgb(249, 179, 179)",
  name: "Full Cream Milk",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["500 ml","450 ml", "6 L"],
  productPageLink: "/full-cream-milk",
  imgSrc: "/",
  imgAlt: "Vardaan Farms Full Cream Milk",
  productBenefit: "Natural & Fresh",
},
{
  bgkeyword: "Balanced",
  bgColor: "rgb(140, 216, 215)",
  name: "Toned Milk",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["450 ml", "500 ml"],
  productPageLink: "/toned-milk",
  imgSrc: "/",
  imgAlt: "Vardaan Farms A2 Desi Cow Milk",
  productBenefit: "Natural & Healthy",
},
{
  bgkeyword: "Light",
  bgColor: "rgb(169, 153, 207)",
  name: "Double Toned Milk",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["400 ml", "500 ml"],
  productPageLink: "/double-toned-milk",
  imgSrc: "/",
  imgAlt: "Vardaan Farms Double Toned Milk",
  productBenefit: "Natural & Healthy",
},
{
  bgkeyword: "Pure",
  bgColor: "rgb(140, 191, 224)",
  name: "Natural Cow Milk",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["350 ml", "500 ml"],
  productPageLink: "/natural-cow-milk",
  imgSrc: "/",
  imgAlt: "Vardaan Farms Natural Cow Milk",
  productBenefit: "Natural & Fresh",
},
{
  bgkeyword: "Rich",
  bgColor: "rgb(107, 105, 114)",
  name: "Buffalo Milk",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["500 ml", "1 L"],
  productPageLink: "/buffalo-milk",
  imgSrc: "/",
  imgAlt: "Vardaan Farms Buffalo Milk",
  productBenefit: "Natural & Nutritious",
},
{
  bgkeyword: "Convenient",
  bgColor: "rgb(242, 141, 146)",
  name: "Family Pack",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["450 ml"],
  productPageLink: "/family-pack",
  imgSrc: "/",
  imgAlt: "Vardaan Farms Family Pack",
  productBenefit: "Natural & Fresh",
},
{
  bgkeyword: "Light",
  bgColor: "rgb(169, 153, 207)",
  name: "Double Toned Milk",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["170 ml"],
  productPageLink: "/double-toned-milk",
  imgSrc: "/",
  imgAlt: "Vardaan Farms Double Toned Milk",
  productBenefit: "Natural & Healthy",
},
{
  bgkeyword: "Refreshing",
  bgColor: "rgb(107, 149, 124)",
  name: "Butter Milk",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["500 ml"],
  productPageLink: "/butter-milk",
  imgSrc: "/",
  imgAlt: "Vardaan Farms Butter Milk",
  productBenefit: "Natural & Tasty",
},
{
  bgkeyword: "Spicy",
  bgColor: "rgb(168, 217, 128)",
  name: "Masala Chach",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["500 ml"],
  productPageLink: "/masala-chach",
  imgSrc: "/",
  imgAlt: "Vardaan Farms Masala Chach",
  productBenefit: "Natural & Refreshing",
},
{
  bgkeyword: "Light",
  bgColor: "rgb(164, 216, 227)",
  name: "Slim Curd",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["400 gm"],
  productPageLink: "/slim-curd",
  imgSrc: "/",
  imgAlt: "Vardaan Farms Slim Curd",
  productBenefit: "Natural & Fresh",
},
{
  bgkeyword: "Creamy",
  bgColor: "rgb(244, 155, 128)",
  name: "Curd",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["400 gm"],
  productPageLink: "/curd",
  imgSrc: "/",
  imgAlt: "Vardaan Farms Curd",
  productBenefit: "Natural & Pure",
},
{
  bgkeyword: "Traditional",
  bgColor: "rgb(248, 232, 156)",
  name: "A2 Desi Cow Ghee",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["500 ml", "1 L"],
  productPageLink: "/a2-desi-cow-ghee",
  imgSrc: "/",
  imgAlt: "Vardaan Farms A2 Desi Cow Ghee",
  productBenefit: "Natural & Pure",
},
{
  bgkeyword: "Flavourfull",
  bgColor: "rgb(247, 244, 216)",
  name: "A2 Desi Buffalo Ghee",
  pera: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum ullam cumque incidunt similique provident quos obcaecati velit consectetur a consequatur quibusdam aut odit, vel magnam!",
  availableIn: ["500 ml", "1 L"],
  productPageLink: "/a2-desi-buffalo-ghee",
  imgSrc: "/",
  imgAlt: "Vardaan Farms A2 Desi Buffalo Ghee",
  productBenefit: "Natural & Rich",
}
]