export const productsData = [
  {
    bgkeyword: "शुद्धता",
    bgColor: "rgb(217 146 100)",
    name: "A2 Desi Cow Milk",
    pera: "Pure A2 milk from native cows, naturally rich and gentle on the stomach. Ideal for kids and elders, perfect for your daily glass, tea, or cereal.",
    availableIn: ["500 ml"],
    productPageLink: "/a2-desi-cow-milk",
    imgSrc: "/vardaanFarms-a2-desi-cow-milk-mockup.png",
    imgAlt: "Vardaan Farms A2 Desi Cow Milk",
    productBenefit: "Natural & Clean",
  },
  {
    bgkeyword: "मखमली",
    bgColor: "rgb(242, 77, 77)",
    name: "Full Cream Milk",
    pera: "Indulgently thick milk with a naturally creamy body that elevates tea, coffee, desserts, and paneer. A wholesome source of energy for growing families.",
    availableIn: ["500 ml","450 ml", "6 L"],
    productPageLink: "/full-cream-milk",
    imgSrc: "/vardaanFarms-full-cream-milk-mockup.png",
    imgAlt: "Vardaan Farms Full Cream Milk",
    productBenefit: "Natural & Fresh",
  },
  {
    bgkeyword: "संतुलन",
    bgColor: "rgb(140, 216, 215)",
    name: "Toned Milk",
    pera: "Balanced nutrition with a lighter profile for everyday fitness. Keeps you active without compromising taste—great for smoothies, tea, and daily cooking.",
    availableIn: ["450 ml", "500 ml"],
    productPageLink: "/toned-milk",
    imgSrc: "/vardaanFarms-toned-milk-mockup.png",
    imgAlt: "Vardaan Farms A2 Desi Cow Milk",
    productBenefit: "Natural & Healthy",
  },
  {
    bgkeyword: "हल्कापन",
    bgColor: "rgb(169, 153, 207)",
    name: "Double Toned Milk",
    pera: "Low-fat and easy to digest, crafted for heart-conscious lifestyles. Enjoy a clean, refreshing taste in your tea and everyday recipes.",
    availableIn: ["400 ml", "500 ml"],
    productPageLink: "/double-toned-milk",
    imgSrc: "/vardaanFarms-double-tonned-milk-mockup.png",
    imgAlt: "Vardaan Farms Double Toned Milk",
    productBenefit: "Natural & Healthy",
  },
  {
    bgkeyword: "खालिस",
    bgColor: "rgb(140, 191, 224)",
    name: "Natural Cow Milk",
    pera: "Fresh, farm-direct cow milk with an honest, authentic taste. No shortcuts—just clean nutrition for your beverages, cooking, and breakfast bowls.",
    availableIn: ["350 ml", "500 ml"],
    productPageLink: "/natural-cow-milk",
    imgSrc: "/vardaanFarms-natural-cow-milk-mockup.png",
    imgAlt: "Vardaan Farms Natural Cow Milk",
    productBenefit: "Natural & Fresh",
  },
  {
    bgkeyword: "ताकत",
    bgColor: "rgb(107, 105, 114)",
    name: "Buffalo Milk",
    pera: "Naturally rich and creamy milk that makes tea, kheer, and desserts truly decadent. High in calcium and protein to support strength and stamina.",
    availableIn: ["500 ml", "1 L"],
    productPageLink: "/buffalo-milk",
    imgSrc: "/vardaanFarms-buffalo-milk-mockup.png",
    imgAlt: "Vardaan Farms Buffalo Milk",
    productBenefit: "Natural & Nutritious",
  },
  {
    bgkeyword: "पारिवारिक",
    bgColor: "rgb(189 0 20 )",
    name: "Family Pack",
    pera: "One pack for the whole household—convenient, consistent, and value-friendly. Stock up with fresh milk that keeps your routine simple and reliable.",
    availableIn: ["450 ml"],
    productPageLink: "/family-pack",
    imgSrc: "/vardaanFarms-family-pack-mockup.png",
    imgAlt: "Vardaan Farms Family Pack",
    productBenefit: "Natural & Fresh",
  },
  {
    bgkeyword: "फिटनेस",
    bgColor: "rgb(169, 153, 207)",
    name: "Double Toned Milk",
    pera: "A light, on-the-go portion that fits busy days and school tiffins. Same crisp taste and low-fat goodness in a handy single-serve pack.",
    availableIn: ["170 ml"],
    productPageLink: "/double-toned-milk",
    imgSrc: "/vardaanFarms-double-tonned-milk-mockup.png",
    imgAlt: "Vardaan Farms Double Toned Milk",
    productBenefit: "Natural & Healthy",
  },
  {
    bgkeyword: "ठंडक",
    bgColor: "rgb(107, 149, 124)",
    name: "Butter Milk",
    pera: "Cooling, refreshing buttermilk with a natural tang that aids digestion. Best enjoyed chilled with meals or as a mid-day pick-me-up.",
    availableIn: ["500 ml"],
    productPageLink: "/butter-milk",
    imgSrc: "/vardaanFarms-butter-milk-mockup.png",
    imgAlt: "Vardaan Farms Butter Milk",
    productBenefit: "Natural & Tasty",
  },
  {
    bgkeyword: "चटखारा",
    bgColor: "rgb(168, 217, 128)",
    name: "Masala Chach",
    pera: "A lively blend of spices and cultured buttermilk for instant freshness. Keeps you cool after meals and pairs beautifully with Indian dishes.",
    availableIn: ["500 ml"],
    productPageLink: "/masala-chach",
    imgSrc: "/vardaanFarms-masala-chach-mockup.png",
    imgAlt: "Vardaan Farms Masala Chach",
    productBenefit: "Natural & Refreshing",
  },
  {
    bgkeyword: "सुकोमल",
    bgColor: "rgb(164, 216, 227)",
    name: "Slim Curd",
    pera: "Low-fat curd that stays smooth and satisfying while supporting your wellness goals. Ideal for raita, parfaits, or a light, protein-rich snack.",
    availableIn: ["400 gm"],
    productPageLink: "/slim-curd",
    imgSrc: "/vardaanFarms-slim-curd-mockup.png",
    imgAlt: "Vardaan Farms Slim Curd",
    productBenefit: "Natural & Fresh",
  },
  {
    bgkeyword: "मलाईपन",
    bgColor: "rgb(244, 155, 128)",
    name: "Curd",
    pera: "Thick, creamy curd with a mild, homestyle taste. Adds balance to everyday meals and supports digestion, from raita to kadhi.",
    availableIn: ["400 gm"],
    productPageLink: "/curd",
    imgSrc: "/vardaanFarms-curd-mockup.png",
    imgAlt: "Vardaan Farms Curd",
    productBenefit: "Natural & Pure",
  },
  {
    bgkeyword: "परंपरा",
    bgColor: "rgb(248, 232, 156)",
    name: "A2 Desi Cow Ghee",
    pera: "Traditional A2 cow ghee, slow-crafted for rich aroma and deep flavor. Perfect for tadkas, sweets, and everyday nourishment.",
    availableIn: ["500 ml", "1 L"],
    productPageLink: "/a2-desi-cow-ghee",
    imgSrc: "/vardaanFarms-a2-desi-cow-ghee-mockup.png",
    imgAlt: "Vardaan Farms A2 Desi Cow Ghee",
    productBenefit: "Natural & Pure",
  },
  {
    bgkeyword: "समृद्धि",
    bgColor: "rgb(247, 244, 216)",
    name: "A2 Desi Buffalo Ghee",
    pera: "Luxuriously rich ghee with a bold, appetizing aroma. Enhances rotis, dal, and festive sweets while delivering wholesome nourishment.",
    availableIn: ["500 ml", "1 L"],
    productPageLink: "/a2-desi-buffalo-ghee",
    imgSrc: "/vardaanFarms-a2-desi-buffalow-ghee-mockup.png",
    imgAlt: "Vardaan Farms A2 Desi Buffalo Ghee",
    productBenefit: "Natural & Rich",
  }
];
