export const specificProductData = {
  "a2-desi-cow-milk": {
    img: [
      "/A2 desi cow milk_1.png",
      "/A2 desi cow milk_2.png",
      "/A2 desi cow milk_3.png",
      "/A2 desi cow milk_4.png",
    ],
    category: "Milk",
    heading: "A2 Desi Cow Milk",
    info: "A2 Desi cow milk from Vardaan Farms is pure, fresh, and natural. Our cows are well-cared for and graze on lush pastures. This milk is easy to digest and packed with nutrients. Enjoy it in your tea, coffee, or straight from the glass. Vardaan Farms brings the goodness of nature to your doorstep.",
    availableIn: ["500 ml"],
    nutritionalFact: {
      Energy: "84.88",
      TotalFat: "4.2",
      saturatedFat: "2.29",
      transFat: "0",
      cholestrol: "7.02",
      carbohydrate: "8.42",
      totalSugar: "8.42",
      addedSugar: "0",
      protein: "3.35",
      sodium: "49.32",
      calcium: "136.48",
    },
    measurmentUnit: "ml",
    bgColor: "rgba(167, 101, 58, 1)",
    textColor: "rgba(255, 255, 255)",
    nutritionbgColor: "#D5B8A6",
    nutritionTextColor: "#1A1A1A",
    // seoData: {
    //   title: "A2 Desi Cow Milk - Vardaan Farms",
    //   description:
    //     "A2 Desi cow milk from Vardaan Farms is pure, fresh, and natural. Our cows are well-cared for and graze on lush pastures. Easy to digest and packed with nutrients.",
    //   keywords:
    //     "A2 Desi cow milk, Vardaan Farms, organic milk, fresh milk, natural milk, nutrient-rich milk, sustainable dairy farming, easy to digest milk, healthy milk",
    //   og: {
    //     title: "A2 Desi Cow Milk - Vardaan Farms",
    //     description:
    //       "A2 Desi cow milk from Vardaan Farms is pure, fresh, and natural. Our cows are well-cared for and graze on lush pastures. Easy to digest and packed with nutrients.",
    //     image: a2DesiCowMilk,
    //     url: "https://www.vardaanfarms.com/product/a2DesiCowMilk",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "A2 Desi Cow Milk - Vardaan Farms",
    //     description:
    //       "A2 Desi cow milk from Vardaan Farms is pure, fresh, and natural. Our cows are well-cared for and graze on lush pastures. Easy to digest and packed with nutrients.",
    //     image: a2DesiCowMilk,
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/a2DesiCowMilk",
    // },
  },
  "full-cream-milk": {
    img: [
      "/Full Cream 500ml milk_1.png",
      "/Full Cream 500ml milk_2.png",
      "/Full Cream 500ml milk_3.png",
      "/Full Cream 500ml milk_4.png",
    ],
    category: "Milk",
    heading: "Full Cream Milk",
    info: "Vardaan Farms' full cream milk is rich and creamy, perfect for those who love a hearty taste. Our cows are fed a natural diet, ensuring the milk is wholesome. Use it to make delicious desserts, smoothies, or just enjoy a glass. Experience the quality and care in every sip from Vardaan Farms.",
    availableIn: ["400ml", "500 ml", "6 l"],
    nutritionalFact: {
      Energy: "87",
      TotalFat: "6.0",
      saturatedFat: "3.8",
      transFat: "0.0",
      cholestrol: "16",
      carbohydrate: "5.0",
      totalSugar: "5.0",
      addedSugar: "0.0",
      protein: "3.2",
      sodium: "42",
      calcium: "120",
    },
    measurmentUnit: "ml",
    bgColor: "#8F1E1E",
    textColor: "#F8F5F2",
    nutritionbgColor: "rgba(217,184,160,1)",
    nutritionTextColor: "rgba(43,29,22,1)",
    // seoData: {
    //   title: "Full Cream Milk - Vardaan Farms",
    //   description:
    //     "Vardaan Farms' full cream milk is rich and creamy, perfect for those who love a hearty taste. Our cows are fed a natural diet, ensuring the milk is wholesome. Use it to make delicious desserts, smoothies, or just enjoy a glass. Experience the quality and care in every sip from Vardaan Farms.",
    //   keywords:
    //     "full cream milk, Vardaan Farms, rich milk, creamy milk, organic milk, fresh milk, natural milk, wholesome milk, nutritious milk, sustainable dairy farming",
    //   og: {
    //     title: "Full Cream Milk - Vardaan Farms",
    //     description:
    //       "Vardaan Farms' full cream milk is rich and creamy, perfect for those who love a hearty taste. Our cows are fed a natural diet, ensuring the milk is wholesome. Use it to make delicious desserts, smoothies, or just enjoy a glass. Experience the quality and care in every sip from Vardaan Farms.",
    //     image: fullCream,
    //     url: "https://www.vardaanfarms.com/product/fullCreamMilk",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Full Cream Milk - Vardaan Farms",
    //     description:
    //       "Vardaan Farms' full cream milk is rich and creamy, perfect for those who love a hearty taste. Our cows are fed a natural diet, ensuring the milk is wholesome. Use it to make delicious desserts, smoothies, or just enjoy a glass. Experience the quality and care in every sip from Vardaan Farms.",
    //     image: fullCream,
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/fullCreamMilk",
    // },
  },
  "toned-milk": {
    img: ["/TM_500_1.png", "/TM_500_2.png", "/TM_500_3.png", "/TM_500_4.png"],
    category: "Milk",
    heading: "Toned Milk",
    info: "Toned milk from Vardaan Farms is a great choice for those who want a lighter option. It retains all the essential nutrients while being lower in fat. Ideal for making your morning cereal, coffee, or tea, it also works well in various recipes. Taste the balance of health and flavor with every drop from Vardaan Farms.",
    availableIn: ["400ml", "500 ml"],
    nutritionalFact: {
      Energy: "58",
      TotalFat: "3.0",
      saturatedFat: "2.0",
      transFat: "0.0",
      cholestrol: "8.0",
      carbohydrate: "4.7",
      totalSugar: "4.7",
      addedSugar: "0.0",
      protein: "3.0",
      sodium: "40",
      calcium: "110",
    },
    measurmentUnit: "ml",
    bgColor: "#4A7A87",
    textColor: "white",
    nutritionbgColor: "#F4E6E5",
    nutritionTextColor: "#1A1A1A",
    // seoData: {
    //   title: "Toned Milk - Vardaan Farms",
    //   description:
    //     "Toned milk from Vardaan Farms is a great choice for those who want a lighter option. It retains all the essential nutrients while being lower in fat. Ideal for making your morning cereal, coffee, or tea, it also works well in various recipes. Taste the balance of health and flavor with every drop from Vardaan Farms.",
    //   keywords:
    //     "toned milk, Vardaan Farms, lighter milk, low-fat milk, organic milk, fresh milk, natural milk, nutritious milk, sustainable dairy farming, healthy milk",
    //   og: {
    //     title: "Toned Milk - Vardaan Farms",
    //     description:
    //       "Toned milk from Vardaan Farms is a great choice for those who want a lighter option. It retains all the essential nutrients while being lower in fat. Ideal for making your morning cereal, coffee, or tea, it also works well in various recipes. Taste the balance of health and flavor with every drop from Vardaan Farms.",
    //     image: tonedMilk,
    //     url: "https://www.vardaanfarms.com/product/tonedMilk",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Toned Milk - Vardaan Farms",
    //     description:
    //       "Toned milk from Vardaan Farms is a great choice for those who want a lighter option. It retains all the essential nutrients while being lower in fat. Ideal for making your morning cereal, coffee, or tea, it also works well in various recipes. Taste the balance of health and flavor with every drop from Vardaan Farms.",
    //     image: tonedMilk,
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/tonedMilk",
    // },
  },
  "double-toned-milk": {
    img: [
      "/Dtm 500 1.png",
      "/Dtm 500 2.png",
      "/Dtm 500 3.png",
      "/Dtm 500 4.png",
    ],
    category: "Milk",
    heading: "Double Toned Milk",
    info: "Vardaan Farms' double toned milk offers a healthy option for those watching their fat intake. It has all the essential nutrients while being light and refreshing. Perfect for making tea, coffee, or enjoying a chilled glass. Bring the freshness and quality of Vardaan Farms into your home.",
    availableIn: ["170 ml", "400 ml", "500 ml"],
    nutritionalFact: {
      Energy: "46",
      TotalFat: "1.5",
      saturatedFat: "1.0",
      transFat: "0.0",
      cholestrol: "4.0",
      carbohydrate: "5.0",
      totalSugar: "5.0",
      addedSugar: "0.0",
      protein: "3.2",
      sodium: "42",
      calcium: "120",
    },
    measurmentUnit: "ml",
    bgColor: "#2F1D5D",
    textColor: "white",
    nutritionbgColor: "rgba(74,122,135,1)",
    nutritionTextColor: "rgba(255,255,255,1)",
    // seoData: {
    //   title: "Double Toned Milk - Vardaan Farms",
    //   description:
    //     "Vardaan Farms' double toned milk offers a healthy option for those watching their fat intake. It has all the essential nutrients while being light and refreshing. Perfect for making tea, coffee, or enjoying a chilled glass. Bring the freshness and quality of Vardaan Farms into your home.",
    //   keywords:
    //     "double toned milk, Vardaan Farms, low-fat milk, healthy milk, organic milk, fresh milk, natural milk, nutritious milk, sustainable dairy farming",
    //   og: {
    //     title: "Double Toned Milk - Vardaan Farms",
    //     description:
    //       "Vardaan Farms' double toned milk offers a healthy option for those watching their fat intake. It has all the essential nutrients while being light and refreshing. Perfect for making tea, coffee, or enjoying a chilled glass. Bring the freshness and quality of Vardaan Farms into your home.",
    //     image: doubleTonedMilk,
    //     url: "https://www.vardaanfarms.com/product/doubleTonedMilk",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Double Toned Milk - Vardaan Farms",
    //     description:
    //       "Vardaan Farms' double toned milk offers a healthy option for those watching their fat intake. It has all the essential nutrients while being light and refreshing. Perfect for making tea, coffee, or enjoying a chilled glass. Bring the freshness and quality of Vardaan Farms into your home.",
    //     image: doubleTonedMilk,
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/doubleTonedMilk",
    // },
  },
  "natural-cow-milk": {
    img: [
      "/Natural cow milk500_1.png",
      "/Natural cow milk500_2.png",
      "/Natural cow milk500_3.png",
      "/Natural cow milk500_4.png",
    ],
    category: "Milk",
    heading: "Natural Cow Milk",
    info: "Vardaan Farms' natural cow milk is fresh and pure, straight from our well-cared-for cows. This milk is packed with natural nutrients and has a rich, authentic taste. Perfect for your daily needs, it can be enjoyed in many ways, from drinking a glass to using it in recipes. Trust in the quality and care of Vardaan Farms.",
    availableIn: ["350 ml", "500 ml"],
    nutritionalFact: {
      Energy: "67",
      TotalFat: "4.0",
      saturatedFat: "2.4",
      transFat: "0.0",
      cholestrol: "12",
      carbohydrate: "4.7",
      totalSugar: "4.7",
      addedSugar: "0.0",
      protein: "3.0",
      sodium: "44",
      calcium: "110",
    },
    measurmentUnit: "ml",
    bgColor: "#184E77",
    textColor: "white",
    nutritionbgColor: "#7DB7DC",
    nutritionTextColor: "#1A1A1A",
    // seoData: {
    //   title: "Natural Cow Milk - Vardaan Farms",
    //   description:
    //     "Vardaan Farms' natural cow milk is fresh and pure, straight from our well-cared-for cows. This milk is packed with natural nutrients and has a rich, authentic taste. Perfect for your daily needs, it can be enjoyed in many ways, from drinking a glass to using it in recipes. Trust in the quality and care of Vardaan Farms.",
    //   keywords:
    //     "natural cow milk, Vardaan Farms, fresh milk, pure milk, organic milk, natural milk, nutrient-rich milk, sustainable dairy farming, healthy milk",
    //   og: {
    //     title: "Natural Cow Milk - Vardaan Farms",
    //     description:
    //       "Vardaan Farms' natural cow milk is fresh and pure, straight from our well-cared-for cows. This milk is packed with natural nutrients and has a rich, authentic taste. Perfect for your daily needs, it can be enjoyed in many ways, from drinking a glass to using it in recipes. Trust in the quality and care of Vardaan Farms.",
    //     image: naturalCowMilk,
    //     url: "https://www.vardaanfarms.com/product/naturalCowMilk",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Natural Cow Milk - Vardaan Farms",
    //     description:
    //       "Vardaan Farms' natural cow milk is fresh and pure, straight from our well-cared-for cows. This milk is packed with natural nutrients and has a rich, authentic taste. Perfect for your daily needs, it can be enjoyed in many ways, from drinking a glass to using it in recipes. Trust in the quality and care of Vardaan Farms.",
    //     image: naturalCowMilk,
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/naturalCowMilk",
    // },
  },
  "buffalo-milk": {
    img: [
      "/Buffalo milk_500ml_1.png",
      "/Buffalo milk_500ml_2.png",
      "/Buffalo milk_500ml_3.png",
      "/Buffalo milk_500ml_4.png",
    ],
    category: "Milk",
    heading: "Buffalo Milk",
    info: "Buffalo milk from Vardaan Farms is thick, creamy, and full of essential nutrients. Ideal for making rich and delicious dairy products, it adds a special touch to your recipes. Our buffaloes are raised with care, ensuring high-quality milk. Experience the richness of buffalo milk from Vardaan Farms in every glass.",
    availableIn: ["500 ml", "1 L"],
    nutritionalFact: {
      Energy: "91",
      TotalFat: "6.5",
      saturatedFat: "4",
      transFat: "0.0",
      cholestrol: "16",
      carbohydrate: "5",
      totalSugar: "5",
      addedSugar: "0.0",
      protein: "3.2",
      sodium: "50",
      calcium: "150",
    },
    measurmentUnit: "ml",
    bgColor: "#0A0A0A",
    textColor: "white",
    nutritionbgColor: "#2B2B2B",
    nutritionTextColor: "#F5F5F0",
    // seoData: {
    //   title: "Buffalo Milk - Vardaan Farms",
    //   description:
    //     "Buffalo milk from Vardaan Farms is thick, creamy, and full of essential nutrients. Ideal for making rich and delicious dairy products, it adds a special touch to your recipes. Our buffaloes are raised with care, ensuring high-quality milk. Experience the richness of buffalo milk from Vardaan Farms in every glass.",
    //   keywords:
    //     "buffalo milk, Vardaan Farms, creamy milk, rich milk, organic milk, fresh milk, natural milk, nutrient-rich milk, sustainable dairy farming, healthy milk",
    //   og: {
    //     title: "Buffalo Milk - Vardaan Farms",
    //     description:
    //       "Buffalo milk from Vardaan Farms is thick, creamy, and full of essential nutrients. Ideal for making rich and delicious dairy products, it adds a special touch to your recipes. Our buffaloes are raised with care, ensuring high-quality milk. Experience the richness of buffalo milk from Vardaan Farms in every glass.",
    //     image: buffaloMilk,
    //     url: "https://www.vardaanfarms.com/product/buffaloMilk",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Buffalo Milk - Vardaan Farms",
    //     description:
    //       "Buffalo milk from Vardaan Farms is thick, creamy, and full of essential nutrients. Ideal for making rich and delicious dairy products, it adds a special touch to your recipes. Our buffaloes are raised with care, ensuring high-quality milk. Experience the richness of buffalo milk from Vardaan Farms in every glass.",
    //     image: buffaloMilk,
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/buffaloMilk",
    // },
  },
  "family-pack": {
    img: [
      "/Family pack _1.png",
      "/Family pack _2.png",
      "/Family pack _3.png",
      "/Family pack _4.png",
    ],
    category: "Milk",
    heading: "Family Pack",
    info: "Vardaan Farms' family pack offers 100% fresh and natural milk, specially homogenized for your family's needs. It's perfect for daily use, ensuring everyone gets the essential nutrients in each glass. Enjoy the quality and purity of Vardaan Farms' milk in a convenient family pack.",
    availableIn: ["450 ml"],
    nutritionalFact: {
      Energy: "74.1",
      TotalFat: "4.5",
      saturatedFat: "2.8",
      transFat: "0.0",
      cholestrol: "12",
      carbohydrate: "5.1",
      totalSugar: "5.1",
      addedSugar: "0.0",
      protein: "3.3",
      sodium: "45",
      calcium: "150",
    },
    measurmentUnit: "ml",
    bgColor: "#9A0010",
    textColor: "white",
    nutritionbgColor: "#E64D5B",
    nutritionTextColor: "#1A1A1A",
    // seoData: {
    //   title: "Family Pack - Vardaan Farms",
    //   description:
    //     "Vardaan Farms' family pack offers 100% fresh and natural milk, specially homogenized for your family's needs. It's perfect for daily use, ensuring everyone gets the essential nutrients in each glass. Enjoy the quality and purity of Vardaan Farms' milk in a convenient family pack.",
    //   keywords:
    //     "family pack, Vardaan Farms, fresh milk, natural milk, organic milk, nutrient-rich milk, sustainable dairy farming, homogenized milk, healthy milk",
    //   og: {
    //     title: "Family Pack - Vardaan Farms",
    //     description:
    //       "Vardaan Farms' family pack offers 100% fresh and natural milk, specially homogenized for your family's needs. It's perfect for daily use, ensuring everyone gets the essential nutrients in each glass. Enjoy the quality and purity of Vardaan Farms' milk in a convenient family pack.",
    //     image: familyPack,
    //     url: "https://www.vardaanfarms.com/product/familyPack",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Family Pack - Vardaan Farms",
    //     description:
    //       "Vardaan Farms' family pack offers 100% fresh and natural milk, specially homogenized for your family's needs. It's perfect for daily use, ensuring everyone gets the essential nutrients in each glass. Enjoy the quality and purity of Vardaan Farms' milk in a convenient family pack.",
    //     image: familyPack,
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/familyPack",
    // },
  },
  "butter-milk": {
    img: ["/Butter milk 1.png", "/Butter milk 2.png", "/Butter milk 3.png"],
    category: "Chach",
    heading: "Butter Milk",
    info: "Vardaan Farms' plain buttermilk is light and refreshing, perfect for staying cool and hydrated. It's made from our pure, natural milk and has a tangy taste that's delightful on its own or used in cooking. Enjoy this healthy and tasty drink, knowing it's made with care at Vardaan Farms.",
    availableIn: ["300 ml"],
    nutritionalFact: {
      Energy: "23",
      TotalFat: "0.7",
      saturatedFat: "0.4",
      transFat: "0.0",
      cholestrol: "2",
      carbohydrate: "2.5",
      totalSugar: "2.5",
      addedSugar: "0.0",
      protein: "1.3",
      sodium: "30",
      calcium: "52",
    },
    measurmentUnit: "ml",
    bgColor: "#01321A",
    textColor: "",
    nutritionbgColor: "",
    nutritionTextColor: "",
    // seoData: {
    //   title: "Butter Milk - Refreshing and Tangy Drink | Vardaan Farms",
    //   description:
    //     "Discover Vardaan Farms' plain buttermilk, a light and refreshing drink made from pure, natural milk. Perfect for staying cool and hydrated. Try it now!",
    //   keywords:
    //     "buttermilk, plain buttermilk, Vardaan Farms, refreshing drink, natural milk, healthy beverage",
    //   og: {
    //     title: "Butter Milk - Vardaan Farms",
    //     description:
    //       "Discover Vardaan Farms' plain buttermilk, a light and refreshing drink made from pure, natural milk. Perfect for staying cool and hydrated. Try it now!",
    //     image: "butterMilk",
    //     url: "https://www.vardaanfarms.com/product/butterMilk",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Butter Milk - Vardaan Farms",
    //     description:
    //       "Discover Vardaan Farms' plain buttermilk, a light and refreshing drink made from pure, natural milk. Perfect for staying cool and hydrated. Try it now!",
    //     image: "butterMilk",
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/butterMilk",
    // },
  },
  "masala-chach": {
    img: ["/Masala chach 1.png", "/Masala chach 2.png", "/Masala chach 3.png"],
    category: "Chach",
    heading: "Masala Chach",
    info: "Masala chach from Vardaan Farms is a refreshing and flavorful drink, made from our natural milk and a blend of spices. It's perfect for cooling down on hot days and aiding digestion. Enjoy it as a tasty and healthy beverage option, crafted with care and quality at Vardaan Farms.",
    availableIn: ["300 ml"],
    nutritionalFact: {
      Energy: "20",
      TotalFat: "1.2",
      saturatedFat: "0.8",
      transFat: "0.0",
      cholestrol: "1.4",
      carbohydrate: "1.2",
      totalSugar: "1.2",
      addedSugar: "0.0",
      protein: "1.2",
      sodium: "263.1",
      calcium: "52",
    },
    measurmentUnit: "ml",
    bgColor: "#3B7210",
    textColor: "",
    nutritionbgColor: "",
    nutritionTextColor: "",
    // seoData: {
    //   title: "Masala Chach - Spiced Buttermilk | Vardaan Farms",
    //   description:
    //     "Enjoy Vardaan Farms' masala chach, a refreshing and flavorful drink made from natural milk and a blend of spices. Perfect for cooling down and aiding digestion.",
    //   keywords:
    //     "masala chach, spiced buttermilk, Vardaan Farms, refreshing drink, natural milk, digestive aid",
    //   og: {
    //     title: "Masala Chach - Vardaan Farms",
    //     description:
    //       "Enjoy Vardaan Farms' masala chach, a refreshing and flavorful drink made from natural milk and a blend of spices. Perfect for cooling down and aiding digestion.",
    //     image: "masalaChach",
    //     url: "https://www.vardaanfarms.com/product/masalaChach",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Masala Chach - Vardaan Farms",
    //     description:
    //       "Enjoy Vardaan Farms' masala chach, a refreshing and flavorful drink made from natural milk and a blend of spices. Perfect for cooling down and aiding digestion.",
    //     image: "masalaChach",
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/masalaChach",
    // },
  },
  "slim-curd": {
    img: ["/Curd 500_1.png", "/Curd 500_2.png", "/Curd 500_3.png"],
    category: "Curd",
    heading: "Slim Curd",
    info: "Vardaan Farms' slim curd is perfect for those seeking a low-fat, nutritious option. Made from our pure, natural milk, this curd is light and creamy, yet packed with essential nutrients. Enjoy it as a healthy snack or add it to your meals for a delicious touch. Taste the care and quality in every spoonful from Vardaan Farms.",
    availableIn: ["160 gm", "350 gm", "950 gm", "5 kg", "15 kg"],
    nutritionalFact: {
      Energy: "40",
      TotalFat: "0.5",
      saturatedFat: "0.0",
      transFat: "0.0",
      cholestrol: "1.3",
      carbohydrate: "4.5",
      totalSugar: "4.5",
      addedSugar: "0.0",
      protein: "4.3",
      sodium: "48",
      calcium: "165",
    },
    measurmentUnit: "gm",
    bgColor: "#6BAAB7",
    textColor: "",
    nutritionbgColor: "",
    nutritionTextColor: "",
    // seoData: {
    //   title: "Slim Curd - Low-Fat Nutritious Curd | Vardaan Farms",
    //   description:
    //     "Try Vardaan Farms' slim curd, a low-fat, nutritious option made from pure, natural milk. Light, creamy, and packed with essential nutrients. Perfect for a healthy snack!",
    //   keywords:
    //     "slim curd, low-fat curd, nutritious curd, Vardaan Farms, natural milk, healthy snack",
    //   og: {
    //     title: "Slim Curd - Vardaan Farms",
    //     description:
    //       "Try Vardaan Farms' slim curd, a low-fat, nutritious option made from pure, natural milk. Light, creamy, and packed with essential nutrients. Perfect for a healthy snack!",
    //     image: "slimCurd",
    //     url: "https://www.vardaanfarms.com/product/slimCurd",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Slim Curd - Vardaan Farms",
    //     description:
    //       "Try Vardaan Farms' slim curd, a low-fat, nutritious option made from pure, natural milk. Light, creamy, and packed with essential nutrients. Perfect for a healthy snack!",
    //     image: "slimCurd",
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/slimCurd",
    // },
  },
  "curd": {
    img: ["/Fresh Curd 1.png", "/Fresh Curd 2.png", "/Fresh Curd 3.png"],
    category: "Curd",
    heading: "Curd",
    info: "Vardaan Farms' curd is rich, creamy, and made from our pure, natural milk. It's packed with essential nutrients and has a smooth texture that enhances any meal. Enjoy it as a refreshing snack or add it to your recipes for a delightful touch. Experience the quality and care in every spoonful from Vardaan Farms.",
    availableIn: ["400 gm"],
    nutritionalFact: {
      Energy: "62",
      TotalFat: "3",
      saturatedFat: "2.1",
      transFat: "0.0",
      cholestrol: "3.4",
      carbohydrate: "5",
      totalSugar: "5",
      addedSugar: "0.0",
      protein: "3.7",
      sodium: "47.6",
      calcium: "168",
    },
    measurmentUnit: "gm",
    bgColor: "#B73700",
    textColor: "",
    nutritionbgColor: "",
    nutritionTextColor: "",
    // seoData: {
    //   title: "Curd - Rich and Creamy | Vardaan Farms",
    //   description:
    //     "Indulge in Vardaan Farms' rich and creamy curd, made from pure, natural milk. Packed with essential nutrients, perfect for enhancing any meal.",
    //   keywords:
    //     "curd, creamy curd, Vardaan Farms, natural milk, nutritious curd, meal enhancement",
    //   og: {
    //     title: "Curd - Vardaan Farms",
    //     description:
    //       "Indulge in Vardaan Farms' rich and creamy curd, made from pure, natural milk. Packed with essential nutrients, perfect for enhancing any meal.",
    //     image: "Curd",
    //     url: "https://www.vardaanfarms.com/product/curd",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Curd - Vardaan Farms",
    //     description:
    //       "Indulge in Vardaan Farms' rich and creamy curd, made from pure, natural milk. Packed with essential nutrients, perfect for enhancing any meal.",
    //     image: "Curd",
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/curd",
    // },
  },
  "a2-desi-cow-ghee": {
    img: [
      "/A2 Desi cow ghee 500_1.png",
      "/A2 Desi cow ghee 500_2.png",
      "/A2 Desi cow ghee 500_3.png",
      "/A2 Desi cow ghee 500_4.png",
    ],
    category: "Ghee",
    heading: "A2 Desi Cow Ghee",
    info: "Vardaan Farms' A2 Desi cow ghee is made from the milk of well-cared-for cows. This ghee is rich in flavor and nutrients, perfect for cooking or adding to your meals. Enjoy the pure, traditional taste and health benefits of our A2 Desi cow ghee, crafted with care and quality at Vardaan Farms.",
    availableIn: ["500 ml", "1 L"],
    nutritionalFact: {
      Energy: "897",
      caloriesFromFat: "897",
      totalFat: "99.72",
      saturatedFatyAcid: "66.71",
      mufa: "26.67",
      pufa: "2.94",
      cholestrol: "159",
      carbohydrate: "<1",
      totalSugar: "0",
      protein: "<0.5",
    },
    measurmentUnit: "gm",
    bgColor: "#B38E28",
    textColor: "",
    nutritionbgColor: "",
    nutritionTextColor: "",
    // seoData: {
    //   title:
    //     "A2 Desi Cow Ghee - Traditional Flavor and Health Benefits | Vardaan Farms",
    //   description:
    //     "Experience the pure, traditional taste and health benefits of Vardaan Farms' A2 Desi cow ghee, made from the milk of well-cared-for cows. Perfect for cooking or adding to meals.",
    //   keywords:
    //     "A2 Desi cow ghee, traditional ghee, Vardaan Farms, natural milk, cooking ghee, healthy ghee",
    //   og: {
    //     title: "A2 Desi Cow Ghee - Vardaan Farms",
    //     description:
    //       "Experience the pure, traditional taste and health benefits of Vardaan Farms' A2 Desi cow ghee, made from the milk of well-cared-for cows. Perfect for cooking or adding to meals.",
    //     image: "a2DesiCowGhee",
    //     url: "https://www.vardaanfarms.com/product/a2DesiCowGhee",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "A2 Desi Cow Ghee - Vardaan Farms",
    //     description:
    //       "Experience the pure, traditional taste and health benefits of Vardaan Farms' A2 Desi cow ghee, made from the milk of well-cared-for cows. Perfect for cooking or adding to meals.",
    //     image: "a2DesiCowGhee",
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/a2DesiCowGhee",
    // },
  },
  "a2-desi-buffalo-ghee": {
    img: [
      "/Buffalo ghee 500_1.png",
      "/Buffalo ghee 500_2.png",
      "/Buffalo ghee 500_3.png",
      "/Buffalo ghee 500_4.png",
    ],
    category: "Ghee",
    heading: "Buffalo Ghee",
    info: "Buffalo ghee from Vardaan Farms is rich and flavorful, perfect for adding depth to your cooking. Made from the milk of well-cared-for buffaloes, it retains all the essential nutrients. Use it in your recipes or enjoy its taste in traditional dishes. Experience the quality and care in every spoonful of Vardaan Farms' buffalo ghee.",
    availableIn: ["500 ml", "1 L"],
    nutritionalFact: {
      Energy: "897.39",
      caloriesFromFat: "897.39",
      totalFat: "99.71",
      saturatedFatyAcid: "66.71",
      mufa: "26.67",
      pufa: "2.94",
      cholestrol: "159",
      carbohydrate: "<1",
      totalSugar: "0",
      protein: "<0.5",
    },
    measurmentUnit: "gm",
    bgColor: "#3A291A",
    textColor: "",
    nutritionbgColor: "",
    nutritionTextColor: "",
    // seoData: {
    //   title: "Buffalo Ghee - Rich and Flavorful | Vardaan Farms",
    //   description:
    //     "Discover the rich and flavorful buffalo ghee from Vardaan Farms, made from the milk of well-cared-for buffaloes. Perfect for adding depth to your cooking.",
    //   keywords:
    //     "buffalo ghee, rich ghee, Vardaan Farms, natural milk, cooking ghee, flavorful ghee",
    //   og: {
    //     title: "Buffalo Ghee - Vardaan Farms",
    //     description:
    //       "Discover the rich and flavorful buffalo ghee from Vardaan Farms, made from the milk of well-cared-for buffaloes. Perfect for adding depth to your cooking.",
    //     image: "buffaloGhee",
    //     url: "https://www.vardaanfarms.com/product/buffaloGhee",
    //   },
    //   twitter: {
    //     card: "summary_large_image",
    //     title: "Buffalo Ghee - Vardaan Farms",
    //     description:
    //       "Discover the rich and flavorful buffalo ghee from Vardaan Farms, made from the milk of well-cared-for buffaloes. Perfect for adding depth to your cooking.",
    //     image: "buffaloGhee",
    //   },
    //   canonical: "https://www.vardaanfarms.com/product/buffaloGhee",
    // },
  },
};
